--Oracle SCHEMA_INFORMATION Queries

SELECT NULL AS TABLE_CATALOG, OWNER AS TABLE_SCHEMA, VIEW_NAME AS TABLE_NAME, TEXT AS VIEW_DEFINITION, 'UNKNOWN' AS CHECK_OPTION, CASE WHEN READ_ONLY = 'N' THEN 'Y' ELSE 'N' END AS IS_UPDATABLE FROM ALL_VIEWS 
WHERE OWNER = 'DBOWLIZER' ORDER BY TABLE_SCHEMA, TABLE_NAME

--Postgres SCHEMA_INFORMATION Queries

SELECT * FROM INFORMATION_SCHEMA.VIEWS ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME

--Mysql SCHEMA_INFOMATION Queries

SELECT TABLE_SCHEMA AS TABLE_CATALOG, NULL AS TABLE_SCHEMA, TABLE_NAME, VIEW_DEFINITION FROM INFORMATION_SCHEMA.VIEWS ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME